[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    lovyan03/LovyanGFX

; ---------------------------------------------------------
; Elecrow ESP32-S3 HMI 7" / CrowPanel 7"
; Module: ESP32-S3-WROOM-1-N4R8
; Flash: 4MB Quad
; PSRAM: 8MB Octal
; ---------------------------------------------------------

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_USB_MODE=0
    -DBOARD_HAS_PSRAM